\ir ../lib/session.sql
-- Explicitly resets only the capstone teaching schema.
DROP SCHEMA IF EXISTS capstone CASCADE;
CREATE SCHEMA capstone;
CREATE TABLE capstone.jobs(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id integer NOT NULL REFERENCES course.projects(id),
 idempotency_key text NOT NULL,
 pool text NOT NULL CHECK(pool IN('cpu','gpu')),
 prompt text NOT NULL,
 priority integer NOT NULL DEFAULT 0,
 status text NOT NULL DEFAULT 'queued' CHECK(status IN('queued','running','succeeded','failed')),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 available_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 attempt integer NOT NULL DEFAULT 0 CHECK(attempt>=0),
 max_attempts integer NOT NULL DEFAULT 3 CHECK(max_attempts BETWEEN 1 AND 20),
 lease_token uuid,
 claimed_by text,
 lease_expires_at timestamptz,
 result jsonb,
 UNIQUE(project_id,idempotency_key),
 CHECK(attempt<=max_attempts),
 CHECK((status='running' AND lease_token IS NOT NULL AND claimed_by IS NOT NULL AND lease_expires_at IS NOT NULL)
    OR (status<>'running' AND lease_token IS NULL AND claimed_by IS NULL AND lease_expires_at IS NULL))
);
CREATE INDEX jobs_claim ON capstone.jobs(project_id,pool,priority DESC,created_at,id)
WHERE status='queued';
CREATE INDEX jobs_expiry ON capstone.jobs(lease_expires_at,id) WHERE status='running';
CREATE TABLE capstone.job_events(
 id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 job_id bigint NOT NULL REFERENCES capstone.jobs(id) ON DELETE CASCADE,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 kind text NOT NULL,
 attempt integer NOT NULL,
 lease_token uuid,
 details jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX job_events_history ON capstone.job_events(job_id,created_at,id);
CREATE TABLE capstone.outbox(
 id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 job_id bigint NOT NULL REFERENCES capstone.jobs(id) ON DELETE CASCADE,
 kind text NOT NULL,
 payload jsonb NOT NULL,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 delivered_at timestamptz,
 UNIQUE(job_id,kind)
);
-- Outbox delivery is at-least-once unless the consumer applies an idempotency
-- protocol. No external API or external-effect worker is implemented here.
INSERT INTO capstone.jobs(project_id,idempotency_key,pool,prompt,priority)
SELECT 1,'demo:'||i,CASE WHEN i%3=0 THEN 'gpu' ELSE 'cpu' END,
 'Summarize synthetic experiment '||i,i%3 FROM generate_series(1,12) g(i);
